config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  get 'availabilities/compare', to: 'availabilities#compare', as: 'availabilities_compare'
  post 'users/:id/compare_availability', to: 'users#compare_availability', as: 'compare_availability'
  resources :users do
    resources :availabilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_before_end_time
  

  private

  def start_time_before_end_time
    if start_time && end_time && start_time >= end_time
      errors.add(:start_time, "must be before end time")
    end
  end

  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :availabilities, dependent: :destroy
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/ }
    validates :name, presence: true, length: { minimum: 2, maximum: 50 }
    validates :phone, presence: true, length: { minimum: 10, maximum: 15 }, format: { with: /\A[0-9]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController

    rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
    before_action :set_availability, only: %i[show edit update destroy]


    def index
      @user = User.find(params[:user_id])
      @availabilities = @user.availabilities
    end

    def show
      @user = @availability.user
    end

    def new
      @user = User.find(params[:user_id])
      @availability = Availability.new
    end

    def edit
      @user = User.find(params[:user_id])
    end

    def create
      @user = User.find(params[:user_id])
      @availability = @user.availabilities.create(availability_params)
      respond_to do |format|
        if @availability.save
          format.html { redirect_to user_availability_path(@user, @availability), notice: "Availability was successfully created." }
          format.json { render :show, status: :created, location: @availability }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @availability.errors, status: :unprocessable_entity }
        end
      end
    end


    def update
      @user = User.find(params[:user_id])
      if @availability.update(availability_params)
        redirect_to user_availability_path(@user, @availability), notice: 'Availability was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:user_id])
      @availability.destroy
      respond_to do |format|
        format.html { redirect_to user_availabilities_path(@user), notice: "Availability was successfully destroyed." }
        format.json { head :no_content }
      end
    end


    def compare
      user_names = params[:user_names]
      users = User.where(name: user_names)
      user_ids = users.pluck(:id)
      @user_availability_pairs = find_common_availability(user_ids)
      render 'compare'
    end


    def find_common_availability(user_ids)
      users = User.find(user_ids)
      user_pairs = users.combination(2).to_a
      common_availability = []
      user_pairs.each do |user_pair|
        availabilities1 = user_pair[0].availabilities.pluck(:start_time, :end_time)
        availabilities2 = user_pair[1].availabilities.pluck(:start_time, :end_time)
        common_slots = calculate_common_slots(availabilities1, availabilities2)
        common_availability << [user_pair, common_slots]
      end
      common_availability
    end

    def calculate_common_slots(availabilities1, availabilities2)
      common_slots = []
      availabilities1.each do |start_time1, end_time1|
        availabilities2.each do |start_time2, end_time2|
          latest_start_time = [start_time1, start_time2].max
          earliest_end_time = [end_time1, end_time2].min
          if latest_start_time < earliest_end_time
            common_slots << [latest_start_time, earliest_end_time]
          end
        end
      end
      common_slots
    end

    private

    def set_availability
      @availability = Availability.find(params[:id])
      @user = @availability.user


    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Availability not found"
      redirect_to user_availabilities_path(params[:user_id])
    end

    def availability_params
      params.require(:availability).permit(:title, :start_time, :end_time, :user_id)
    end

    def catch_not_found
      flash[:alert] = "Availability not found"
      if params[:user_id]
        redirect_to user_availabilities_path(params[:user_id])
      else
        redirect_to users_path
      end
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @users= User.all
  end

  # GET /users/new
  def new
    @users= User.all
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @users= User.all
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User.find(params[:id])
    @users = User.all # set @users variable here
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end
  

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  def compare_availability
    redirect_to availabilities_compare_path(user_names: params[:user_names])
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone, :email)
    end

    def catch_not_found
      flash[:alert] = "User not found"
      redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/availabilities/_form.html.erb
<%= form_for [@user, availability], class: "form-floating" do |form| %>
  <div class="form-group pt-5">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_time, class: "form-label" %>
    <%= form.datetime_local_field :start_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :end_time, class: "form-label" %>
    <%= form.datetime_local_field :end_time, class: "form-control" %>
  </div>

  <div class="form-group" >
    <%= form.submit "Submit", id:"availability-form-submit" %>
  </div>
<% end %>

app/views/availabilities/compare.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand">Compare Users Availability</h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          
        </ul>
      </div>
    </div>
</nav>
<h1 class= "pb-3 pt-2">Compare Availabilities</h1>
<h6 class = "pb-3 pt-2">Select two or more users to compare your availablities</h6>

<%= form_tag(availabilities_compare_path, method: :get) do %>
  <% User.all.each do |user| %>
    <%= check_box_tag 'user_names[]', user.name %>
    <%= label_tag user.name %>
  <% end %>
  <%= submit_tag "Compare", id:"compare_button", disabled: true %>
<% end %>

<h1 class= "pb-3 pt-2">Common Availabilities</h1>

<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% else %>
  <% @user_availability_pairs.each do |user_pair, common_slots| %>
    <h2><%= user_pair.map(&:name).join(" and ") %></h2>
    <% if common_slots.any? %>
      <ul>
        <% common_slots.each do |slot| %>
          <li>
            <%= l(slot[0], format: :short) %> to <%= l(slot[1], format: :short) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No common availabilities found</p>
    <% end %>
  <% end %>
<% end %>

app/views/availabilities/edit.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand"><%=" Editing #{@user.name}'s #{@availability.title} Availability" %> </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
          <li><%= link_to 'Add Availability', new_user_availability_path(@user), class: "nav-link"%></li>
          <li><%= link_to "Back to #{@user.name}'s Profile",@user, class: "nav-link" %></li>
        </ul>
      </div>
    </div>
</nav>
<%= render 'form', availability: @availability %>

app/views/availabilities/index.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand"><%=" #{@user.name}'s Availabilities" %></h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
          <li><%= link_to 'Add Availability', new_user_availability_path(@user), class: "nav-link"%></li>
          <li><%= link_to "Back to #{@user.name}'s Profile", @user, class: "nav-link" %></li>
        </ul>
      </div>
    </div>
</nav>
 <table class="table text-center">
    
    <thead>
        <th class=" pt-5" colspan = "4" >Availabilities </th>
    </thead>
    <tbody>
      <tr class="fw-bold">
          <td scope="col">Title</td>
          <td scope="col">Start Time</td>
          <td scope="col">End Time</td>
          <td scope="col"></td>
      </tr>

      <% @user.availabilities.each do |availability| %>
        <tr>
          <td><%= availability.title %></td>
          <td><%= availability.start_time %></td>
          <td><%= availability.end_time %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Availability Actions
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Destroy', user_availability_path(availability.user, availability), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
                <li><%=  link_to 'Edit', edit_user_availability_path(availability.user, availability), class: "dropdown-item" %> </li>
                <li><%= link_to 'Show',  user_availability_path(availability.user, availability), class: "dropdown-item"%></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/availabilities/new.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand"> <%=" New Availability for #{@user.name}" %> </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
           <li><%= link_to "Back to #{@user.name}'s Profile", user_availabilities_path(@user), class: "nav-link" %></li>
        </ul>
      </div>
    </div>
</nav>
<%= render 'form', availability: @availability %>

app/views/availabilities/show.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand"><%=" #{@user.name}'s #{@availability.title} Availability" %> </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
          <li><%= link_to 'Add Availability', new_user_availability_path(@user), class: "nav-link"%></li>
          <li><%= link_to "Back to #{@user.name}'s Profile", @user, class: "nav-link" %></li>
        </ul>
      </div>
    </div>
</nav>
  <table class="table text-center">
    
    <thead>
        <th class=" pt-5" colspan = "4" >Availabilities </th>
    </thead>
    <tbody>
      <tr class="fw-bold">
          <td scope="col">Title</td>
          <td scope="col">Start Time</td>
          <td scope="col">End Time</td>
          <td scope="col"></td>
      </tr>
      <% @user.availabilities.each do |availability| %>
        <tr>
          <td><%= availability.title %></td>
          <td><%= availability.start_time %></td>
          <td><%= availability.end_time %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Availability Actions
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Destroy', user_availability_path(availability.user, availability), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
                <li><%=  link_to 'Edit', edit_user_availability_path(availability.user, availability), class: "dropdown-item" %> </li>
                <li><%= link_to 'Show',  user_availability_path(availability.user, availability), class: "dropdown-item"%></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindTime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- In your view file -->  
    <%= stylesheet_link_tag "users", "availabilities" %>
     
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand"> <%="Editing #{@user.name}'s Info" %> </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
              <li><%= link_to 'View Availabilities', user_availabilities_path(@user), class:"nav-link " %></li>
          </li>
          <li><%= link_to 'Add Availability', new_user_availability_path(@user), class:"nav-link " %></li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Exisiting Users
            </a>
            <ul class="dropdown-menu">
              <% @users.each do |user| %>
                <li><%= link_to user.name, user, class: "dropdown-item"%></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand">Users</h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Exisiting Users
            </a>
            <ul class="dropdown-menu">
              <% @users.each do |user| %>
                <li><%= link_to user.name, user, class: "dropdown-item"%></li>
                
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>

<body >
  <div class="accordion pt-5" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          See All Users
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= user.name %></td>
                    <td><%= user.phone %></td>
                    <td><%= user.email %></td>
                    <td>
                      <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        User Actions
                        </button>
                        <ul class="dropdown-menu">
                          <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
                          <li><%=  link_to 'Edit', edit_user_path(user), class: "dropdown-item" %> </li>
                          <li><%= link_to 'Show', user, class: "dropdown-item"%></li>
                          <li><%= link_to 'Add Availability', new_user_availability_path(user), class: "dropdown-item"%></li>
                          <li><%= link_to 'View Availabilities', user_availabilities_path(user), class: "dropdown-item"%></li>
                        </ul>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Select From Exisiting Users
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <div class = "dropdown">
            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" >Click Here to Select User</button>
            <ul class="dropdown-menu">
                <% @users.each do |user| %>
                  <li><%= link_to user.name, user, class: "dropdown-item"%></li>
                  
                <% end %>
              </ul>
            </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<% if notice %>
  <div id="notice"><%= notice %></div>
<% end %>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <h1 class="navbar-brand"> <%="#{@user.name}'s Profile" %> </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to 'Home', users_path, class:"nav-link "  %>
          </li>
          <li class="nav-item">
              <li><%= link_to 'View Availabilities', user_availabilities_path(@user), class:"nav-link " %></li>
          </li>
          <li><%= link_to 'Add Availability', new_user_availability_path(@user), class:"nav-link " %></li>
          <li class="nav-item">
            <%= link_to 'Compare Availablities', availabilities_compare_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'New User', new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Exisiting Users
            </a>
            <ul class="dropdown-menu">
              <% @users.each do |user| %>
                <li><%= link_to user.name, user, class: "dropdown-item"%></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>

  <table class=" pt-5 text-center" >
    <thead  colspan = "4">
      <tr>
        <th class=" pt-5">Name</th>
        <th class=" pt-5">Phone</th>
        <th class=" pt-5">Email</th>
        <th class=" pt-5"></th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= @user.name %></td>
          <td><%= @user.phone %></td>
          <td><%= @user.email %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              User Actions
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
                <li><%=  link_to 'Edit', edit_user_path(@user), class: "dropdown-item" %> </li>
                <li><%= link_to 'Show', @user, class: "dropdown-item"%></li>
                <li><%= link_to 'Add Availability', new_user_availability_path(@user), class: "dropdown-item"%></li>
                <li><%= link_to 'View Availabilities', user_availabilities_path(@user), class: "dropdown-item"%></li>
              </ul>
            </div>
          </td>
        </tr>
    </tbody>
  </table>
  <table class="table text-center">
    
    <thead>
        <th class=" pt-5" colspan = "4" >Availabilities </th>
    </thead>
    <tbody>
      <tr class="fw-bold">
          <td scope="col">Title</td>
          <td scope="col">Start Time</td>
          <td scope="col">End Time</td>
          <td scope="col"></td>
      </tr>
      <% @user.availabilities.each do |availability| %>
        <tr>
          <td><%= availability.title %></td>
          <td><%= availability.start_time %></td>
          <td><%= availability.end_time %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Availability Actions
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Destroy', user_availability_path(availability.user, availability), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
                <li><%=  link_to 'Edit', edit_user_availability_path(availability.user, availability), class: "dropdown-item" %> </li>
                <li><%= link_to 'Show',  user_availability_path(availability.user, availability), class: "dropdown-item"%></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>